exports.COOKIE_ACCESS_TOKEN_EXPIRATION = 60 * 1000; // HOW LONG THE USER CAN BE AUTHENTICATED WHEN SUCCESS IN LOGIN?
exports.COOKIE_PUBLIC_CSRF_TOKEN_EXPIRATION = 60 * 1000; // HOW LONG THE PUBLIC CSRF TO BE EXPIRED
exports.COOKIE_LOGIN_AUTH_TOKEN_EXPIRATION = 60 * 1000; // HOW LONG THE MULTI FACTOR AUTHENTICATION TO BE ENDED BEFORE LOGIN AGAIN?