// ------------- AUTHENTICATE JWT TOKEN MIDDLEWARE -------------
exports.NO_JWT_TOKEN_AUTHENTICATE_JWT_TOKEN = 300;
exports.INVALID_JWT_TOKEN_AUTHENTICATE_JWT_TOKEN = 301;
exports.NO_USER_FOUND_IN_DATABASE_INSIDE_JWT_DECODED_TOKEN_AUTHENTICATE_JWT_TOKEN = 302;

// ------------- VERIFY PRIVATE CSRF TOKEN MIDDLEWARE -------------
exports.NO_CSRF_TOKEN_VERIFY_PRIVATE_CSRF_TOKEN = 303;
exports.INVALID_CSRF_TOKEN_VERIFY_PRIVATE_CSRF_TOKEN = 304;

// ------------- VERIFY PUBLIC CSRF TOKEN MIDDLEWARE -------------
exports.NO_CSRF_TOKEN_VERIFY_PUBLIC_CSRF_TOKEN = 305;
exports.INVALID_CSRF_TOKEN_VERIFY_PUBLIC_CSRF_TOKEN = 306;

// ------------- LOGIN CONTROLLER -------------
exports.INCOMPLETE_LOGIN_FORM = 307;
exports.INVALID_USER_INPUT_LOGIN = 308;
exports.USERNAME_NOT_EXIST_LOGIN = 309; 
exports.PASSWORD_NOT_MATCH_LOGIN = 310; 
exports.USER_SSO_ACCOUNT_LOGIN = 311;

// ------------- VERIFICATION CODE LOGIN CONTROLLER -------------
exports.INCOMPLETE_LOGIN_FORM_VERIFICATION_CODE_LOGIN = 312;
exports.INVALID_OR_EXPIRED_MULTI_FACTOR_AUTHENTICATION_LOGIN_CODE = 313;
exports.INVALID_USER_INPUT_VERIFICATION_CODE_LOGIN = 314;
exports.USER_NOT_EXIST_VERIFICATION_CODE_LOGIN = 315;
exports.VERIFICATION_CODE_LOGIN_NOT_MATCH = 316;
exports.EXPIRED_VERIFICATION_CODE_LOGIN = 317;

// -------------- GOOGLE AUTHENTICATION CODE LOGIN CONTROLLER ----------------
exports.INCOMPLETE_LOGIN_FORM_GOOGLE_AUTHENTICATION_CODE_LOGIN = 318;
exports.INVALID_OR_EXPIRED_MULTI_FACTOR_AUTHENTICATION_LOGIN_CODE_GOOGLE_AUTHENTICATION_CODE_LOGIN = 319;
exports.INVALID_USER_INPUT_GOOGLE_AUTHENTICATION_CODE_LOGIN = 320;
exports.INVALID_GOOGLE_AUTHENTICATION_CODE_LOGIN = 321;
exports.INVALID_GOOGLE_AUTHENTICATION_CODE_LOGIN = 322;


// ------------- REGISTER CONTROLLER -------------
exports.INCOMPLETE_REGISTER_FORM = 323;
exports.INVALID_USER_INPUT_REGISTER = 324;
exports.USERNAME_EXIST_REGISTER = 325;
exports.EMAIL_EXIST_REGISTER = 326;

// ------------- ACTIVATE CONTROLLER -------------
exports.INCOMPLETE_REGISTER_FORM_ACTIVATE = 327;
exports.INVALID_USER_INPUT_REGISTER_ACTIVATE = 328;
exports.USERNAME_EXIST_REGISTER_ACTIVATE = 329;
exports.EMAIL_EXIST_REGISTER_ACTIVATE = 330;
exports.EXPIRED_ACCOUNT_ACTIVATION_JWT_TOKEN_OR_INVALID_ACCOUNT_ACTIVATION_JWT_TOKEN = 331;
exports.NO_ACCOUNT_ACTIVATION_JWT_TOKEN = 332;

// ------------- FORGOT PASSWORD CONTROLLER -------------
exports.INCOMPLETE_FORGOT_PASSWORD_FORM = 333;
exports.INVALID_USER_INPUT_FORGOT_PASSWORD = 334;
exports.EMAIL_NOT_EXIST_FORGOT_PASSWORD = 335;
exports.USER_SSO_ACCOUNT_FORGOT_PASSWORD = 336;

// ------------- RESET PASSWORD CONTROLLER -------------
exports.NO_JWT_TOKEN_OR_CSRF_TOKEN_RESET_PASSWORD = 337;
exports.EXPIRED_LINK_OR_INVALID_CSRF_TOKEN_RESET_PASSWORD = 338;
exports.EXPIRED_LINK_OR_INVALID_JWT_TOKEN_RESET_PASSWORD = 339;
exports.INCOMPLETE_RESET_PASSWORD_FORM = 340;
exports.PASSWORD_REPEAT_PASSWORD_NOT_MATCH_RESET_PASSWORD_FORM = 341;
exports.INVALID_USER_INPUT_RESET_PASSWORD = 342;
exports.EMAIL_NOT_EXIST_RESET_PASSWORD = 343;
exports.USER_SSO_ACCOUNT_RESET_PASSWORD = 344;
exports.INVALID_CSRF_TOKEN_RESET_PASSWORD = 345;

// ------------- ACCOUNT RECOVERY RESET PASSWORD VERIFY TOKEN CONTROLLER -------------
exports.NO_JWT_TOKEN_OR_CSRF_TOKEN_ACCOUNT_RECOVERY_RESET_PASSWORD_VERIFY_TOKEN = 346;
exports.EXPIRED_LINK_OR_INVALID_CSRF_TOKEN_ACCOUNT_RECOVERY_RESET_PASSWORD_VERIFY_TOKEN = 347;
exports.EXPIRED_LINK_OR_INVALID_JWT_TOKEN_ACCOUNT_RECOVERY_RESET_PASSWORD_VERIFY_TOKEN = 348;
exports.INCOMPLETE_FORGOT_PASSWORD_FORM_ACCOUNT_RECOVERY_RESET_PASSWORD_VERIFY_TOKEN = 349;
exports.INVALID_USER_INPUT_FORGOT_PASSWORD_ACCOUNT_RECOVERY_RESET_PASSWORD_VERIFY_TOKEN = 350;
exports.INVALID_CSRF_TOKEN_ACCOUNT_RECOVERY_RESET_PASSWORD_VERIFY_TOKEN = 351;

// ------------- SSO GOOGLE IDENTITY SERVICES -------------
exports.NO_SSO_JWT_TOKEN_SSO_GOOGLE_IDENTITY_SERVICES = 352;
exports.INCOMPLETE_CREDENTIAL_SSO_GOOGLE_IDENTITY_SERVICES = 353;
exports.INVALID_CREDENTIAL_SSO_GOOGLE_IDENTITY_SERVICES = 354;

// ------------- SSO FIREBASE FACEBOOK -------------
exports.NO_SSO_JWT_TOKEN_SSO_FIREBASE_FACEBOOK = 355;
exports.INCOMPLETE_CREDENTIAL_SSO_FIREBASE_FACEBOOK = 356;
exports.INVALID_CREDENTIAL_SSO_FIREBASE_FACEBOOK = 357;

// ------------- SSO FIREBASE GOOGLE -------------
exports.NO_SSO_JWT_TOKEN_SSO_FIREBASE_GOOGLE = 358;
exports.INCOMPLETE_CREDENTIAL_SSO_FIREBASE_GOOGLE = 359;
exports.EMAIL_NOT_VERIFIED_SSO_FIREBASE_GOOGLE = 360;
exports.INVALID_CREDENTIAL_SSO_FIREBASE_GOOGLE = 361;

// ------------- MODEL MONGOOSE VALIDATION ERROR -------------
exports.MONGOOSE_VALIDATION_ERROR = 499;

// ------------- SERVER ERROR -------------
exports.SERVER_ERROR = 500;

