// ------------- AUTHENTICATE JWT TOKEN MIDDLEWARE -------------
exports.NO_JWT_TOKEN_AUTHENTICATE_JWT_TOKEN = 300;
exports.INVALID_JWT_TOKEN_AUTHENTICATE_JWT_TOKEN = 301;
exports.NO_USER_FOUND_IN_DATABASE_INSIDE_JWT_DECODED_TOKEN_AUTHENTICATE_JWT_TOKEN = 302;

// ------------- VERIFY PRIVATE CSRF TOKEN MIDDLEWARE -------------
exports.NO_CSRF_TOKEN_VERIFY_PRIVATE_CSRF_TOKEN = 303;
exports.INVALID_CSRF_TOKEN_VERIFY_PRIVATE_CSRF_TOKEN = 304;

// ------------- VERIFY PUBLIC CSRF TOKEN MIDDLEWARE -------------
exports.NO_CSRF_TOKEN_VERIFY_PUBLIC_CSRF_TOKEN = 305;
exports.INVALID_CSRF_TOKEN_VERIFY_PUBLIC_CSRF_TOKEN = 306;

// ------------- LOGIN CONTROLLER -------------
exports.INCOMPLETE_LOGIN_FORM = 307;
exports.INVALID_USER_INPUT_LOGIN = 308;
exports.USERNAME_NOT_EXIST_LOGIN = 309; 
exports.PASSWORD_NOT_MATCH_LOGIN = 310; 

// ------------- REGISTER CONTROLLER -------------
exports.INCOMPLETE_REGISTER_FORM = 311;
exports.INVALID_USER_INPUT_REGISTER = 312;
exports.USERNAME_EXIST_REGISTER = 313;
exports.EMAIL_EXIST_REGISTER = 314;

// ------------- ACTIVATE CONTROLLER -------------
exports.INCOMPLETE_REGISTER_FORM_ACTIVATE = 315;
exports.INVALID_USER_INPUT_REGISTER_ACTIVATE = 316;
exports.USERNAME_EXIST_REGISTER_ACTIVATE = 317;
exports.EMAIL_EXIST_REGISTER_ACTIVATE = 318;
exports.EXPIRED_ACCOUNT_ACTIVATION_JWT_TOKEN_OR_INVALID_ACCOUNT_ACTIVATION_JWT_TOKEN = 319;
exports.NO_ACCOUNT_ACTIVATION_JWT_TOKEN = 320;

// ------------- FORGOT PASSWORD CONTROLLER -------------
exports.INCOMPLETE_FORGOT_PASSWORD_FORM = 321;
exports.INVALID_USER_INPUT_FORGOT_PASSWORD = 322;
exports.EMAIL_NOT_EXIST_FORGOT_PASSWORD = 323;

// ------------- RESET PASSWORD CONTROLLER -------------
exports.NO_JWT_TOKEN_OR_CSRF_TOKEN_RESET_PASSWORD = 324;
exports.EXPIRED_LINK_OR_INVALID_CSRF_TOKEN_RESET_PASSWORD = 325;
exports.EXPIRED_LINK_OR_INVALID_JWT_TOKEN_RESET_PASSWORD = 326;
exports.INCOMPLETE_RESET_PASSWORD_FORM = 327;
exports.PASSWORD_REPEAT_PASSWORD_NOT_MATCH_RESET_PASSWORD_FORM = 328;
exports.INVALID_USER_INPUT_RESET_PASSWORD = 329;
exports.EMAIL_NOT_EXIST_RESET_PASSWORD = 330;
exports.INVALID_CSRF_TOKEN_RESET_PASSWORD = 331;

// ------------- ACCOUNT RECOVERY RESET PASSWORD VERIFY TOKEN CONTROLLER -------------
exports.NO_JWT_TOKEN_OR_CSRF_TOKEN_ACCOUNT_RECOVERY_RESET_PASSWORD_VERIFY_TOKEN = 332;
exports.EXPIRED_LINK_OR_INVALID_CSRF_TOKEN_ACCOUNT_RECOVERY_RESET_PASSWORD_VERIFY_TOKEN = 333;
exports.EXPIRED_LINK_OR_INVALID_JWT_TOKEN_ACCOUNT_RECOVERY_RESET_PASSWORD_VERIFY_TOKEN = 334;
exports.INCOMPLETE_FORGOT_PASSWORD_FORM_ACCOUNT_RECOVERY_RESET_PASSWORD_VERIFY_TOKEN = 335;
exports.INVALID_USER_INPUT_FORGOT_PASSWORD_ACCOUNT_RECOVERY_RESET_PASSWORD_VERIFY_TOKEN = 336;
exports.INVALID_CSRF_TOKEN_ACCOUNT_RECOVERY_RESET_PASSWORD_VERIFY_TOKEN = 337;

// ------------- MODEL MONGOOSE VALIDATION ERROR -------------
exports.MONGOOSE_VALIDATION_ERROR = 499;

// ------------- SERVER ERROR -------------
exports.SERVER_ERROR = 500;

